-- Fresh Postgres (Railway or other). SQLite still uses 0001/0002/0003 *.sql.
-- Role GRANTs for Supabase (anon/authenticated/service_role) are best-effort.

create table if not exists operators (
  authority text primary key,
  name text,
  uri text,
  fee_bps integer
);

create table if not exists mandates (
  id text primary key,
  owner text not null,
  operator text not null,
  state text not null,
  created_ts bigint,
  strategy_id text
);

create table if not exists receipts (
  id integer generated by default as identity primary key,
  mandate_id text not null,
  kind text not null,
  refused integer not null default 0,
  reason text,
  nonce integer,
  sig text,
  ts bigint,
  strategy_id text,
  operator text,
  venue text,
  token text,
  amount bigint,
  action_type text
);

create table if not exists strategies (
  strategy_id text primary key,
  operator text not null,
  name text,
  slug text,
  template_json text not null,
  published_at bigint
);

create index if not exists receipts_mandate_idx on receipts (mandate_id, id desc);
create index if not exists receipts_public_ts_idx on receipts (ts desc, id desc);
create index if not exists receipts_strategy_idx on receipts (strategy_id);
create index if not exists mandates_strategy_idx on mandates (strategy_id);

drop view if exists public.public_receipts;
create view public.public_receipts as
select
  cast(id as text) as receipt_id,
  ts,
  mandate_id as mandate,
  operator,
  coalesce(
    action_type,
    case
      when venue in ('demo_swap', 'demoSwap') then 'swap'
      when venue in ('demo_yield', 'demoYield') then 'deposit'
      else null
    end
  ) as action_type,
  venue,
  token,
  amount,
  case
    when refused = 1 or kind = 'ActionRefused' then 'blocked'
    else 'allowed'
  end as result,
  case
    when refused = 1 or kind = 'ActionRefused' then reason
    else null
  end as block_reason,
  sig as tx_sig
from receipts
where kind in ('ActionExecuted', 'ActionRefused')
  and ts is not null;

comment on view public.public_receipts is 'Public Receipt Read Model (SPEC.md). Exposed fields only.';

do $$ begin
  execute 'revoke all on public.public_receipts from public';
exception when undefined_object then null;
end $$;
do $$ begin
  execute 'revoke all on public.public_receipts from anon';
exception when undefined_object then null;
end $$;
do $$ begin
  execute 'revoke all on public.public_receipts from authenticated';
exception when undefined_object then null;
end $$;
do $$ begin
  execute 'grant select on public.public_receipts to service_role';
exception when undefined_object then null;
end $$;
