export const copy = {
  product: "Float",
  skip: "Skip to content",
  nav: {
    marketplace: "Marketplace",
    subscribe: "Subscribe",
    kill: "Kill switch",
    bot: "Bot",
    docs: "Docs",
    markov: "Markov",
    menu: "Menu",
  },
  marketplace: {
    eyebrow: "Marketplace",
    empty: "No strategies yet — publish the first.",
    error: "The API did not answer. Start it, then try again.",
    loading: "Loading strategies…",
    stream: "Live receipts",
    streamEmpty: "No receipts yet. The first action or refusal lands here.",
    chainLabel: "On-chain record",
    subscribe: "Subscribe",
    record: "Record",
  },
  strategy: {
    eyebrow: "Strategy",
    subscribe: "Subscribe",
    operator: "Operator",
    refusalsFilter: "Refusals only",
    allFilter: "All receipts",
    empty: "No receipts on this strategy yet.",
    loading: "Loading strategy…",
    missing: "Unknown strategy.",
    labeled: "labeled redteam",
    fanOut: "Fan-out tick",
    sweep: "Redteam sweep",
    sweepToast: "Redteam sweep landed",
  },
  subscribe: {
    eyebrow: "Subscribe",
    title: "Tighten your caps.",
    lede: "You stay the owner. The operator gets a fenced right to act. Caps can only tighten versus the template.",
    stepTemplate: "Template",
    stepCaps: "Your caps",
    stepDiff: "Yours vs template",
    yoursCol: "Yours",
    yourCaps: "your caps",
    perTx: "Per-trade cap (USDC-d)",
    daily: "Daily cap (USDC-d)",
    expiry: "Expiry (days)",
    fundLabel: "Fund (USDC-d)",
    stepFund: "Fund",
    next: "Continue",
    back: "Back",
    fund: "Fund mandate",
    pending: "Pending…",
    created: "Mandate created",
    tightenOnly: "Overrides may only tighten the published template.",
    loading: "Loading template…",
  },
  console: {
    eyebrow: "Console",
    balances: "Balances",
    pauseHelp: "Pause freezes the operator. Revoke is terminal. Neither moves your funds.",
    live: "Live.",
    paused: "Paused.",
    revoked: "Revoked.",
    withdrawLine: "Withdraw still points at you.",
    loading: "Loading mandate…",
    missing: "Mandate not found. Nothing moved.",
    receipts: "Receipts",
    receiptsEmpty: "No receipts yet.",
    pause: "Pause mandate",
    pausedToast: "Mandate paused",
    resume: "Resume mandate",
    resumedToast: "Mandate resumed",
    revoke: "Revoke mandate",
    revokedToast: "Mandate revoked",
    withdraw: "Withdraw to owner",
    withdrawnToast: "Withdrawn to owner",
    tick: "Tick operator",
    overCap: "Force over-cap",
    botLinked: "Linked to @markov_float_bot",
  },
  kill: {
    eyebrow: "Kill switch",
    title: "Freeze every operator.",
    fundsStay: "Funds stay put.",
    lede: "One control per mandate. Pause or revoke. Neither moves capital. Withdraw still works in every state.",
    pauseAll: "Pause all active",
    pausedAll: "Active mandates paused",
    arm: "Arm revoke",
    confirm: "Revoke mandate",
    empty: "No mandates.",
    loading: "Loading mandates…",
  },
  operator: {
    eyebrow: "Operator",
    missing: "Unknown operator.",
    publicRecord: "Public record.",
    labeled: "Labeled adversary.",
  },
  bot: {
    eyebrow: "Bot",
    title: "Emergency bot.",
    lede: "The bot can pause or revoke. It cannot trade, spend, or withdraw.",
    linked: "Linked to @markov_float_bot",
    unlinked: "Bot username unset. Set TELEGRAM_BOT_USERNAME.",
    threshold: "Refusal burst threshold",
    thresholdHelp: "Alert when this many refusals land on one strategy in ten minutes.",
  },
  demo: {
    four: "Run four-beat demo",
    fourBusy: "Running four-beat…",
    vault: "Run strategy-vault demo",
    vaultBusy: "Running strategy-vault…",
  },
  errors: {
    generic: "Something broke. Your keys are still yours.",
    tryAgain: "Try again",
    notFound: "Page not found. The marketplace is still here.",
    marketplace: "Marketplace",
  },
  toast: {
    failed: "The request did not complete. Try again.",
  },
  sheet: {
    eyebrow: "Component sheet",
    title: "Float objects.",
    default: "Default",
    empty: "Empty",
    loading: "Loading",
    error: "Error",
    arriving: "Arriving",
  },
} as const;
